### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by ozbl** [ugorsahin/TalkingHeads#25] opened 2023-08-15 09:25 UTC
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by ugorsahin** [comment] 2023-08-15 11:21
Hey, I can't reproduce it. Can you pass `verbose=True` and share debug information with me?

**Comment by WeixinYang** [comment] 2023-08-16 13:17
> 

driver_version = 116

**Comment by ugorsahin** [comment] 2023-08-16 14:49
Hey, undetected-chrome doesn't support Chrome versions after 114. There are other people facing the same issue at the moment. Please take a look at:
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1478
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1338
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1465

You can roll back to Chrome 114 to make it work again. Otherwise you have to wait for 115 and 116 support.

**Comment by ugorsahin** [comment] 2023-08-22 10:52
For the time being you can run the following command to fix the issue temporarily.


```
pip install -e git+https://github.com/jdholtz/undetected-chrome driver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver
```

**Comment by FriedaMarvin** [comment] 2023-08-22 13:33
> For the time being you can run the following command to fix the issue temporarily.
> 
> ```
> pip install -e git+https://github.com/jdholtz/undetected-chrome driver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver
> ```

is this correct?
getting the following error, please check when free :)

ERROR: Invalid requirement: 'driver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver'
Hint: = is not a valid operator. Did you mean == ?

**Comment by itsciccio** [comment] 2023-08-24 14:40
Thanks for the fix @ugorsahin! My team and I were facing the exact same issue and that temporary solution worked. I hope that an official fix will be released soon.

**Comment by ugorsahin** [comment] 2024-03-03 16:54
Closed due to inactivity

**Closed by ugorsahin** 2024-03-03 16:54 UTC
